[package]
name = "ssp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
tar = "0.4.44"
zstd = "0.13.3"
bytemuck = { version = "1.25.0", features = ['derive'] }
duckdb = { version = "1.4.4", features = ["bundled"] }
crossbeam = "0.8.4"
arrow = "56"
parquet = "56"
